#include "shop.h"

static const ShopItemInfo ITEMS[ITEM_COUNT] = {
    [ITEM_WILDCARD]        = { STR_ITEM_WILDCARD_NAME,        STR_ITEM_WILDCARD_DESC,        3, false },
    [ITEM_MEMORY_FLUSH]    = { STR_ITEM_MEMORY_FLUSH_NAME,    STR_ITEM_MEMORY_FLUSH_DESC,    2, false },
    [ITEM_BUFFER_RELOAD]   = { STR_ITEM_BUFFER_RELOAD_NAME,   STR_ITEM_BUFFER_RELOAD_DESC,   3, false },
    [ITEM_COMPILER_PATCH]  = { STR_ITEM_COMPILER_PATCH_NAME,  STR_ITEM_COMPILER_PATCH_DESC,  4, false },
    [ITEM_NULL_POINTER]    = { STR_ITEM_NULL_POINTER_NAME,    STR_ITEM_NULL_POINTER_DESC,    3, false },
    [ITEM_REDUNDANT_WARM]  = { STR_ITEM_REDUNDANT_WARM_NAME,  STR_ITEM_REDUNDANT_WARM_DESC,  6, true  },
    [ITEM_REDUNDANT_COOL]  = { STR_ITEM_REDUNDANT_COOL_NAME,  STR_ITEM_REDUNDANT_COOL_DESC,  6, true  },
    [ITEM_REDUNDANT_COLOR] = { STR_ITEM_REDUNDANT_COLOR_NAME, STR_ITEM_REDUNDANT_COLOR_DESC, 11, true },
    [ITEM_BANKER_CHIP]     = { STR_ITEM_BANKER_CHIP_NAME,     STR_ITEM_BANKER_CHIP_DESC,     8, true  },
    [ITEM_TRY_CATCH]       = { STR_ITEM_TRY_CATCH_NAME,       STR_ITEM_TRY_CATCH_DESC,       6, true  },
    [ITEM_PREFETCH]           = { STR_ITEM_PREFETCH_NAME,             STR_ITEM_PREFETCH_DESC,             7, true },
    [ITEM_GARBAGE_COLLECTOR]  = { STR_ITEM_GARBAGE_COLLECTOR_NAME,    STR_ITEM_GARBAGE_COLLECTOR_DESC,    6, true },
    [ITEM_OVERCLOCK]          = { STR_ITEM_OVERCLOCK_NAME,            STR_ITEM_OVERCLOCK_DESC,            5, true },
    [ITEM_ROLLBACK]           = { STR_ITEM_ROLLBACK_NAME,             STR_ITEM_ROLLBACK_DESC,             3, false },
    [ITEM_MULTITHREAD]        = { STR_ITEM_MULTITHREAD_NAME,          STR_ITEM_MULTITHREAD_DESC,          4, false },
    [ITEM_CACHE_BOOST]        = { STR_ITEM_CACHE_BOOST_NAME,          STR_ITEM_CACHE_BOOST_DESC,          6, true },
    [ITEM_LOOP_UNROLL]        = { STR_ITEM_LOOP_UNROLL_NAME,          STR_ITEM_LOOP_UNROLL_DESC,          6, true },
    [ITEM_DEFRAG]             = { STR_ITEM_DEFRAG_NAME,               STR_ITEM_DEFRAG_DESC,               3, false },
    [ITEM_JIT_COMPILER]       = { STR_ITEM_JIT_COMPILER_NAME,         STR_ITEM_JIT_COMPILER_DESC,         7, true },
    [ITEM_CLUB_CACHE]         = { STR_ITEM_CLUB_CACHE_NAME,           STR_ITEM_CLUB_CACHE_DESC,           6, true },
    [ITEM_EXPLOIT]            = { STR_ITEM_EXPLOIT_NAME,              STR_ITEM_EXPLOIT_DESC,              8, true },
    [ITEM_CORE_DUMP]          = { STR_ITEM_CORE_DUMP_NAME,            STR_ITEM_CORE_DUMP_DESC,            6, true },
    [ITEM_RACE_CONDITION]     = { STR_ITEM_RACE_CONDITION_NAME,       STR_ITEM_RACE_CONDITION_DESC,       5, true },
    [ITEM_STACK_CANARY]       = { STR_ITEM_STACK_CANARY_NAME,         STR_ITEM_STACK_CANARY_DESC,         5, true },
    [ITEM_AMORTIZATION]       = { STR_ITEM_AMORTIZATION_NAME,         STR_ITEM_AMORTIZATION_DESC,         6, true },
    [ITEM_DEBT_CEILING]       = { STR_ITEM_DEBT_CEILING_NAME,         STR_ITEM_DEBT_CEILING_DESC,         5, true },
    [ITEM_COMPOUND_INTEREST]  = { STR_ITEM_COMPOUND_INTEREST_NAME,    STR_ITEM_COMPOUND_INTEREST_DESC,    5, true },
    [ITEM_EMERGENCY_FUND]     = { STR_ITEM_EMERGENCY_FUND_NAME,       STR_ITEM_EMERGENCY_FUND_DESC,       4, true },
    [ITEM_DIAGONAL_CACHE]     = { STR_ITEM_DIAGONAL_CACHE_NAME,       STR_ITEM_DIAGONAL_CACHE_DESC,       6, true },
    [ITEM_DEALLOCATOR]        = { STR_ITEM_DEALLOCATOR_NAME,          STR_ITEM_DEALLOCATOR_DESC,          6, true },
    [ITEM_COMPRESSION_ALGORITHM] = { STR_ITEM_COMPRESSION_ALGORITHM_NAME, STR_ITEM_COMPRESSION_ALGORITHM_DESC, 7, true },
    [ITEM_STACK_REWIND]       = { STR_ITEM_STACK_REWIND_NAME,         STR_ITEM_STACK_REWIND_DESC,         5, false },
    [ITEM_FORCE_PUSH]         = { STR_ITEM_FORCE_PUSH_NAME,           STR_ITEM_FORCE_PUSH_DESC,           5, false },
};

const ShopItemInfo *shop_getItemInfo(ShopItemId id)
{
    return &ITEMS[id];
}
