#ifndef SHOP_H
#define SHOP_H

#include <stdbool.h>

typedef enum ShopItemId {
    ITEM_WILDCARD = 0,
    ITEM_MEMORY_FLUSH,
    ITEM_BUFFER_RELOAD,
    ITEM_COMPILER_PATCH,
    ITEM_NULL_POINTER,
    ITEM_REDUNDANT_WARM,
    ITEM_REDUNDANT_COOL,
    ITEM_REDUNDANT_COLOR, 
    ITEM_BANKER_CHIP,
    ITEM_TRY_CATCH,
    ITEM_PREFETCH,
    ITEM_GARBAGE_COLLECTOR,
    ITEM_OVERCLOCK,
    ITEM_ROLLBACK,
    ITEM_MULTITHREAD,
    ITEM_CACHE_BOOST,
    ITEM_LOOP_UNROLL,
    ITEM_DEFRAG,
    ITEM_JIT_COMPILER,
    ITEM_CLUB_CACHE,
    ITEM_EXPLOIT,
    ITEM_CORE_DUMP,
    ITEM_RACE_CONDITION,
    ITEM_STACK_CANARY,
    ITEM_AMORTIZATION,
    ITEM_DEBT_CEILING,
    ITEM_COMPOUND_INTEREST,
    ITEM_EMERGENCY_FUND,
    ITEM_DIAGONAL_CACHE,
    ITEM_DEALLOCATOR,
    ITEM_COMPRESSION_ALGORITHM,
    ITEM_STACK_REWIND,
    ITEM_FORCE_PUSH,
    ITEM_COUNT
} ShopItemId;

typedef struct ShopItemInfo {
    const char *name;
    const char *description;
    int  cost;
    bool isModule;
} ShopItemInfo;

const ShopItemInfo *shop_getItemInfo(ShopItemId id);

#endif
